# Generated by Django 3.1 on 2020-08-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status post', 'verbose_name_plural': 'status posts'},
        ),
    ]
