# Generated by Django 3.1 on 2020-08-05 23:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200805_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, default='No image', null=True, upload_to=api.models.uploadDirectory),
        ),
    ]
